rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

headbar:
  avatar: false
  title: true
  description: true

exclude_generators:
  - index

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /images/favicon-32x32.png
twitter:
google_plus:
fb_admins:
fb_app_id:

node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false
