name: Tests
run-name: Testing and linting of the code-base
on: [pull_request]
jobs:
  lint:
    name: Test source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Install NPM dependencies
        run: npm i
      - name: Lint
        uses: wearerequired/lint-action@v2.1.0
      - name: Check TypeScript
        run: npm run tsc
      - name: Run Jest
        run: CI=true npm run cra:test
